version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blog-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hyagxyurwtc1"
s3_prefix = "blog-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

